version: 2
updates:

- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  groups:
    wordpress-packages:
      patterns:
        - "@wordpress/*"
  labels:
  - dependencies
  versioning-strategy: increase

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  labels:
    - dependencies
